spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:telegramMem
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    drop-first: false
    change-log: classpath:/db/changelog/db.changelog-master.xml

telegram:
  token: 5322821400:AAFD6Ge2Sd2KokSs027Pp_5sz5vizruABaE

